baseURL = "https://blogzen2020.github.io"
languageCode = "id"
defaultContentLanguage = "id"
title = "Zen"
theme = "hugo-theme-dream"

copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons BY NC SA 4.0'

googleAnalytics = "UA-98295641-1"

disqusShortname = "menghafalquran"

enableRobotsTXT = true

hasCJKLanguage = true

# Paginate = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]

# https://gohugo.io/news/0.60.0-relnotes/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # background = "black"
  backgroundImage = "/background.jpg"
  linkColor = "seagreen"

  author = "Zen"
  description = "Zen"
  avatar = "/yy.jpg"
  motto = "cepat tepat tuntas"
  categoriesLimitInHeader = 6
  # headerBottomText = ""

  rss = true

  utterancesRepo = "blogzen2020/blogzen2020.github.io"
  
  email = "muhzaini30@gmail.com"
  # twitter = "g1eny0ung"
  facebook = "mzaini30"
  instagram = "mzaini30"
  # linkedin = "g1eny0ung"
  github = "mzaini30"
  # stackoverflow = "5676489/g1eny0ung"
  # codepen = "g1eny0ung"

  siteStartYear = 2020

  favicon = "/favicon.ico"

  highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["ocaml"]
  highlightjsTheme = "gruvbox-light"
  highlightjsThemeDark = "gruvbox-dark"

  # search
  enableSearch = true

  # options
  showSummaryCoverInPost = true

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404 = true